dist: trusty

sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -U setuptools
  - pip install -r requirements-dev.txt

script:
  - flake8 aiogmaps/
  - pytest tests/

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email: false
